USE [SaleManagementSystem]
GO
/****** Object:  Table [dbo].[CATEGORY]    Script Date: 14/01/2026 18:15:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORY](
	[ID_CATEGORY] [int] IDENTITY(1,1) NOT NULL,
	[NAME_CATEGORY] [varchar](100) NOT NULL,
	[DESCRIPTION] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CATEGORY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLIENT]    Script Date: 14/01/2026 18:15:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENT](
	[ID_CLIENT] [int] IDENTITY(1,1) NOT NULL,
	[NAME_CLIENT] [varchar](100) NOT NULL,
	[CPF] [char](11) NOT NULL,
	[EMAIL] [varchar](100) NOT NULL,
	[PHONE] [varchar](15) NULL,
	[REGISTER_DATE] [date] NOT NULL,
	[STATUS] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CLIENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCT]    Script Date: 14/01/2026 18:15:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCT](
	[ID_PRODUCT] [int] IDENTITY(1,1) NOT NULL,
	[NAME_PRODUCT] [varchar](100) NOT NULL,
	[PRICE] [decimal](10, 2) NOT NULL,
	[STOCK] [int] NOT NULL,
	[ID_CATEGORY] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PRODUCT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALE]    Script Date: 14/01/2026 18:15:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALE](
	[ID_SALE] [int] IDENTITY(1,1) NOT NULL,
	[SALE_DATE] [date] NOT NULL,
	[TOTAL_PRICE] [decimal](10, 2) NOT NULL,
	[PAYMENT_METHOD] [varchar](30) NOT NULL,
	[ID_CLIENT] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_SALE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALE_ITEM]    Script Date: 14/01/2026 18:15:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALE_ITEM](
	[ID_SALE_ITEM] [int] IDENTITY(1,1) NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[UNIT_PRICE] [decimal](10, 2) NOT NULL,
	[TOTAL] [decimal](10, 2) NOT NULL,
	[ID_SALE] [int] NOT NULL,
	[ID_PRODUCT] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_SALE_ITEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCT]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCT_CATEGORY] FOREIGN KEY([ID_CATEGORY])
REFERENCES [dbo].[CATEGORY] ([ID_CATEGORY])
GO
ALTER TABLE [dbo].[PRODUCT] CHECK CONSTRAINT [FK_PRODUCT_CATEGORY]
GO
ALTER TABLE [dbo].[SALE]  WITH CHECK ADD  CONSTRAINT [FK_SALE_CLIENT] FOREIGN KEY([ID_CLIENT])
REFERENCES [dbo].[CLIENT] ([ID_CLIENT])
GO
ALTER TABLE [dbo].[SALE] CHECK CONSTRAINT [FK_SALE_CLIENT]
GO
ALTER TABLE [dbo].[SALE_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_SALE_ITEM_PRODUCT] FOREIGN KEY([ID_PRODUCT])
REFERENCES [dbo].[PRODUCT] ([ID_PRODUCT])
GO
ALTER TABLE [dbo].[SALE_ITEM] CHECK CONSTRAINT [FK_SALE_ITEM_PRODUCT]
GO
ALTER TABLE [dbo].[SALE_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_SALE_ITEM_SALE] FOREIGN KEY([ID_SALE])
REFERENCES [dbo].[SALE] ([ID_SALE])
GO
ALTER TABLE [dbo].[SALE_ITEM] CHECK CONSTRAINT [FK_SALE_ITEM_SALE]
GO
