-- PROCEDURES

-- 1) PROCEDURE QUE LISTA AS VENDAS DE UM ID ESPECIFICO 
CREATE PROCEDURE SP_GET_SALES_BY_CLIENT
    @ID_CLIENT INT
AS
BEGIN
    SELECT
        S.ID_SALE,
        S.SALE_DATE,
        S.TOTAL_PRICE,
        S.PAYMENT_METHOD
    FROM SALE S
    WHERE S.ID_CLIENT = @ID_CLIENT;
END;

EXEC SP_GET_SALES_BY_CLIENT @ID_CLIENT = 1;

-- 2) PROCEDURE PARA INSERIR UMA NOVA VENDA 
CREATE PROCEDURE SP_INSERT_NEW_SALE
     @SALE_DATE DATE,
	 @TOTAL_PRICE DECIMAL(10,2),
	 @PAYMENT_METHOD VARCHAR(30),
	 @ID_CLIENT INT
AS
BEGIN
     INSERT INTO SALE(
	                  SALE_DATE, 
	                  TOTAL_PRICE, 
					  PAYMENT_METHOD, 
					  ID_CLIENT
					  ) 
	                  VALUES(
					  @SALE_DATE, 
					  @TOTAL_PRICE, 
					  @PAYMENT_METHOD, 
					  @ID_CLIENT
					  );
END;


EXEC SP_INSERT_NEW_SALE
     @SALE_DATE = '2025-12-25',
	 @TOTAL_PRICE = 15.90,
	 @PAYMENT_METHOD = 'Pix',
	 @ID_CLIENT = 4;

	 SELECT * FROM SALE;

-- 3) PROCEDURE QUE ATUALIZA O ESTOQUE DE UM PRODUTO
CREATE PROCEDURE SP_UPDATE_PRODUCT_STOCK
       @ID_PRODUCT INT,
	   @NEW_STOCK INT
AS
BEGIN
     UPDATE PRODUCT
	 SET STOCK = @NEW_STOCK
	 WHERE ID_PRODUCT = @ID_PRODUCT;
END;

EXEC SP_UPDATE_PRODUCT_STOCK
     @ID_PRODUCT = 1,
	 @NEW_STOCK = 8;

	 SELECT * FROM PRODUCT;

-- 4) PROCEDURE PARA INSERIR UMA NOVA CATEGORIA
CREATE PROCEDURE SP_INSERT_NEW_CATEGORY
       @NAME_CATEGORY VARCHAR(100),
	   @DESCRIPTION VARCHAR(100)
AS
BEGIN
     INSERT INTO CATEGORY(
	                     NAME_CATEGORY, 
						 DESCRIPTION
						 ) 
						 VALUES(
						 @NAME_CATEGORY, 
						 @DESCRIPTION
						 );
END;

EXEC SP_INSERT_NEW_CATEGORY 
     @NAME_CATEGORY = 'Roupas',
	 @DESCRIPTION = 'Roupas femininas e masculinas diversas';

	 SELECT * FROM CATEGORY;

-- 5) PROCEDURE QUE CALCULA O TOTAL DE UMA VENDA SOMANDO OS ITENS E ATUALIZANDO O VALOR 
CREATE PROCEDURE SP_CALCULATE_SALE_TOTAL
       @ID_SALE INT
AS
BEGIN
     DECLARE @TOTAL DECIMAL(10,2);
	 
	 SELECT @TOTAL = ISNULL(SUM(TOTAL),0)
	 FROM SALE_ITEM 
	 WHERE ID_SALE = @ID_SALE;

	 UPDATE SALE 
	 SET TOTAL_PRICE = @TOTAL 
	 WHERE ID_SALE = @ID_SALE;
END;

EXEC SP_CALCULATE_SALE_TOTAL @ID_SALE = 1;

SELECT * FROM SALE;
SELECT * FROM SALE_ITEM;

-- 6) PROCEDURE QUE BLOQUEIA A VENDA PARA CLIENTES COM STATUS INATIVO
CREATE PROCEDURE SP_INSERT_NEW_SALE_IF_CLIENT_IS_ACTIVE
       @SALE_DATE DATE,
       @TOTAL_PRICE DECIMAL(10,2),
	   @PAYMENT_METHOD VARCHAR(30),
	   @ID_CLIENT INT
AS
BEGIN
      IF EXISTS(
	            SELECT 1 
				FROM CLIENT 
				WHERE ID_CLIENT = @ID_CLIENT 
				AND STATUS = 1
				)
BEGIN
      INSERT INTO SALE(
	                   SALE_DATE, 
					   TOTAL_PRICE, 
					   PAYMENT_METHOD, 
					   ID_CLIENT
					   ) 
					   VALUES(
					   @SALE_DATE, 
					   @TOTAL_PRICE, 
					   @PAYMENT_METHOD,
					   @ID_CLIENT
					   );
END
ELSE
BEGIN
      PRINT 'Venda n�o permitida: cliente com status inativo.'
END
END;

EXEC SP_INSERT_NEW_SALE_IF_CLIENT_IS_ACTIVE
    @SALE_DATE = '2026-01-15',
    @TOTAL_PRICE = 250.00,
    @PAYMENT_METHOD = 'Cart�o de cr�dito',
    @ID_CLIENT = 3;


