-- 17) CLIENTES QUE COMPRAM MAIS DE UM PRODUTO
SELECT 
    C.NAME_CLIENT,
    SUM(SI.QUANTITY) AS TOTAL_PRODUCTS
FROM CLIENT C
INNER JOIN SALE S ON C.ID_CLIENT = S.ID_CLIENT
INNER JOIN SALE_ITEM SI ON S.ID_SALE = SI.ID_SALE
GROUP BY C.NAME_CLIENT
HAVING SUM(SI.QUANTITY) > 1;
