
-- CONSULTAS COM SELECTS E JOINS

-- 1)  NOME DOS CLIENTES QUE N�O EFETUARAM NENHUMA COMPRA
SELECT C.ID_CLIENT, C.NAME_CLIENT FROM CLIENT C 
LEFT JOIN SALE S ON C.ID_CLIENT = S.ID_CLIENT 
WHERE S.ID_CLIENT IS NULL;

-- 2)  TODAS AS VENDAS COM NOME DO CLIENTE E TOTAL
SELECT C.NAME_CLIENT, S.ID_CLIENT, S.TOTAL_PRICE 
FROM SALE S
INNER JOIN CLIENT C ON C.ID_CLIENT = S.ID_CLIENT;

-- 3) TODOS OS PRODUTOS VENDIDOS EM CADA VENDA COM NOME DO CLIENTE E DO PRODUTO
SELECT S.ID_SALE, S.SALE_DATE, C.NAME_CLIENT, P.NAME_PRODUCT, SI.QUANTITY, SI.TOTAL
FROM SALE S
INNER JOIN CLIENT C ON S.ID_CLIENT = C.ID_CLIENT
INNER JOIN SALE_ITEM SI ON S.ID_SALE = SI.ID_SALE
INNER JOIN PRODUCT P ON SI.ID_PRODUCT = P.ID_PRODUCT
ORDER BY S.ID_SALE;

-- 4) TOTAL GASTO POR CADA CLIENTE
SELECT C.ID_CLIENT, C.NAME_CLIENT, SUM(S.TOTAL_PRICE) AS TOTAL_SPENT FROM CLIENT C
INNER JOIN SALE S ON C.ID_CLIENT = S.ID_CLIENT
GROUP BY C.ID_CLIENT, C.NAME_CLIENT
ORDER BY TOTAL_SPENT DESC;

-- 5) LISTA DE PRODUTOS E SUAS CATEGORIAS
SELECT P.ID_PRODUCT, P.NAME_PRODUCT, CT.NAME_CATEGORY, CT.DESCRIPTION FROM CATEGORY CT
INNER JOIN PRODUCT P ON P.ID_CATEGORY = CT.ID_CATEGORY;

-- 6) VENDAS COM MAIS DE 1 ITEM, MOSTRANDO NOME DO CLIENTE, PRODUTO E A QUANTIDADE
SELECT S.ID_SALE, C.NAME_CLIENT, P.NAME_PRODUCT, SI.QUANTITY FROM SALE_ITEM SI
INNER JOIN PRODUCT P ON SI.ID_PRODUCT = P.ID_PRODUCT
INNER JOIN SALE S ON S.ID_SALE = SI.ID_SALE
INNER JOIN CLIENT C ON S.ID_CLIENT = C.ID_CLIENT
WHERE S.ID_SALE IN (
    SELECT ID_SALE
    FROM SALE_ITEM
    GROUP BY ID_SALE
    HAVING COUNT(ID_SALE_ITEM) > 1
)
ORDER BY S.ID_SALE;

-- 7) VENDAS REALIZADAS EM 2025 COM NOME DO CLIENTE E OS PRODUTOS COMPRADOS
SELECT S.ID_SALE, S.SALE_DATE, C.NAME_CLIENT, P.NAME_PRODUCT, SI.QUANTITY FROM SALE S
INNER JOIN CLIENT C ON C.ID_CLIENT = S.ID_CLIENT 
INNER JOIN SALE_ITEM SI ON SI.ID_SALE = S.ID_SALE
INNER JOIN PRODUCT P ON P.ID_PRODUCT = SI.ID_PRODUCT
WHERE YEAR (S.SALE_DATE) = 2025
ORDER BY SALE_DATE ASC;

-- 8) LISTA DE TODAS AS CATEGORIAS INCLUINDO CATEGORIAS SEM PRODUTOS
SELECT CT.NAME_CATEGORY, P.NAME_PRODUCT FROM CATEGORY CT
LEFT JOIN PRODUCT P ON P.ID_CATEGORY = CT.ID_CATEGORY;

-- 9) LISTA DE CLIENTES E PRODUTOS COMPRADOS, INCLUINDO CLIENTES SEM COMPRAS
SELECT C.ID_CLIENT, C.NAME_CLIENT, ISNULL(SUM(SI.QUANTITY), 0) AS TOTAL_PRODUCTS FROM CLIENT C
LEFT JOIN SALE S ON C.ID_CLIENT = S.ID_CLIENT
LEFT JOIN SALE_ITEM SI ON S.ID_SALE = SI.ID_SALE
GROUP BY C.ID_CLIENT, C.NAME_CLIENT
ORDER BY TOTAL_PRODUCTS DESC;

-- 10) LISTA DE PRODUTOS VENDIDOS E N�O VENDIDOS
SELECT P.ID_PRODUCT, P.NAME_PRODUCT, SI.ID_SALE, SI.QUANTITY FROM SALE_ITEM SI
RIGHT JOIN PRODUCT P ON P.ID_PRODUCT = SI.ID_PRODUCT
ORDER BY P.NAME_PRODUCT;

-- 11) TOTAL DE VENDAS POR CLIENTE
SELECT C.ID_CLIENT, C.NAME_CLIENT, 
COUNT(S.ID_SALE) AS SALE_QUANTITY, 
SUM(S.TOTAL_PRICE) AS TOTAL_SALE FROM SALE S
LEFT JOIN CLIENT C ON C.ID_CLIENT = S.ID_CLIENT
GROUP BY C.ID_CLIENT, C.NAME_CLIENT
ORDER BY TOTAL_SALE DESC;

-- 12) QUANTIDADE TOTAL DE PRODUTOS VENDIDOS POR CATEGORIA
SELECT CT.ID_CATEGORY, CT.NAME_CATEGORY,  
SUM(SI.QUANTITY) AS TOTAL_SALE FROM SALE_ITEM SI
LEFT JOIN PRODUCT P ON P.ID_PRODUCT = SI.ID_PRODUCT
LEFT JOIN CATEGORY CT ON CT.ID_CATEGORY = P.ID_CATEGORY
GROUP BY CT.ID_CATEGORY, CT.NAME_CATEGORY
ORDER BY TOTAL_SALE DESC;

-- 13) MEDIA DE VALOR DAS VENDAS POR M�TODO DE PAGAMENTO
SELECT PAYMENT_METHOD, CAST(AVG(TOTAL_PRICE) AS DECIMAL (10,2)) AS SALE_AVG FROM SALE GROUP BY PAYMENT_METHOD;

-- 14) CLIENTE QUE GASTOU MAIS DINHEIRO
SELECT TOP 1 C.ID_CLIENT, C.NAME_CLIENT, SUM(S.TOTAL_PRICE) AS TOTAL_SPENT FROM CLIENT C 
INNER JOIN SALE S ON C.ID_CLIENT = S.ID_CLIENT
GROUP BY C.ID_CLIENT, C.NAME_CLIENT
ORDER BY TOTAL_SPENT DESC;

-- 15) PRODUTO MAIS VENDIDO EM QUANTIDADE
SELECT TOP 1 P.ID_PRODUCT, P.NAME_PRODUCT, SUM(SI.QUANTITY) AS TOTAL_SOLD FROM PRODUCT P
INNER JOIN SALE_ITEM SI ON SI.ID_PRODUCT = P.ID_PRODUCT
GROUP BY P.ID_PRODUCT, P.NAME_PRODUCT
ORDER BY TOTAL_SOLD DESC;

-- 16) PRODUTOS MAIS CARO QUE 100.00
SELECT NAME_PRODUCT, MAX(PRICE) AS MAX_PRICE
FROM PRODUCT 
GROUP BY  NAME_PRODUCT
HAVING MAX(PRICE) >= 100.00;

-- 17) CLIENTES QUE COMPRAM MAIS DE UM PRODUTO
SELECT C.NAME_CLIENT, SUM(SI.QUANTITY) AS TOTAL_PRODUCTS FROM CLIENT C
INNER JOIN SALE S ON C.ID_CLIENT = S.ID_CLIENT
INNER JOIN SALE_ITEM SI ON SI.ID_SALE = S.ID_SALE
GROUP BY NAME_CLIENT
HAVING SUM(SI.QUANTITY) > 1;

