-- TRIGGERS

-- 1) TRIGGER QUE ATUALIZA ESTOQUE DE UM ITEM QUANDO VENDIDO
CREATE TRIGGER TR_UPDATE_STOCK_AFTER_SALE
ON SALE_ITEM
AFTER INSERT
AS
BEGIN
    UPDATE P
    SET P.STOCK = P.STOCK - I.QUANTITY
    FROM PRODUCT P
    INNER JOIN INSERTED I ON P.ID_PRODUCT = I.ID_PRODUCT;
END;

INSERT INTO SALE_ITEM (QUANTITY, UNIT_PRICE, TOTAL, ID_SALE, ID_PRODUCT)
VALUES (2, 66.99, 133.98, 1, 2);

SELECT NAME_PRODUCT, STOCK FROM PRODUCT WHERE ID_PRODUCT = 2;

-- 2) TRIGGER QUE IMPEDE VENDA DE CLIENTE INATIVO
CREATE TRIGGER TR_SALE_BLOCKED_FOR_INACTIVE_CLIENTS
ON SALE
AFTER INSERT
AS
BEGIN
     IF EXISTS(
	           SELECT 1 FROM INSERTED I 
			   INNER JOIN CLIENT C ON C.ID_CLIENT = I.ID_CLIENT
			   WHERE C.STATUS = 0
			   )
BEGIN 
		ROLLBACK TRANSACTION;
		PRINT 'Venda n�o permitida: cliente com status inativo'
	END
END;

INSERT INTO SALE (SALE_DATE, TOTAL_PRICE, PAYMENT_METHOD, ID_CLIENT)
VALUES ('2026-01-20', 100.00, 'Pix', 3); 

-- 3) TIGGER QUE IMPEDE EXCLUS�O DE CLIENTE QUE POSSUI VENDA
CREATE TRIGGER TR_BLOCKED_DELETE_IF_CLIENT_WITH_SALE
ON CLIENT 
INSTEAD OF DELETE
AS
BEGIN
     IF EXISTS(SELECT 1 FROM SALE S
	           INNER JOIN DELETED D ON D.ID_CLIENT = S.ID_CLIENT)
BEGIN
	PRINT 'Exclus�o n�o permitida: cliente possui vendas'
END
ELSE
BEGIN
	 DELETE FROM CLIENT WHERE ID_CLIENT IN(SELECT ID_CLIENT FROM DELETED)
END
END;

DELETE FROM CLIENT WHERE ID_CLIENT = 1; 

-- 4) TRIGGER QUE IMPEDE A EXCLUS�O DE UM PRODUTO QUE J� FOI VENDIDO
CREATE TRIGGER TR_BLOCKED_DELETE_IF_PRODUCT_WITH_SALE
ON PRODUCT
INSTEAD OF DELETE
AS
BEGIN
     IF EXISTS(
	           SELECT 1 FROM SALE_ITEM SI
			   INNER JOIN DELETED D ON D.ID_PRODUCT = SI.ID_PRODUCT)
BEGIN
      PRINT 'Exclus�o n�o permitida: produto j� foi vendido'
END
ELSE
BEGIN
      DELETE FROM SALE_ITEM WHERE ID_PRODUCT IN(SELECT ID_PRODUCT FROM DELETED)
END
END;

DELETE FROM PRODUCT WHERE ID_PRODUCT = 1;

-- 5) TRIGGER QUE IMPEDE ALTERA��O DE PRE�O DO PRODUTO QUE J� FOI VENDIDO
CREATE TRIGGER TR_BLOCKED_UPDATE_IF_PRODUCT_WITH_SALE
ON PRODUCT
AFTER UPDATE
AS
BEGIN
     IF UPDATE(PRICE)
	 BEGIN
     IF EXISTS(
	           SELECT 1 FROM SALE_ITEM SI 
	           INNER JOIN INSERTED I ON I.ID_PRODUCT = SI.ID_PRODUCT)
BEGIN
     ROLLBACK TRANSACTION
     PRINT 'Altera��o n�o permitida: produto j� foi vendido'
END
END
END;

UPDATE PRODUCT
SET PRICE = 60.00
WHERE ID_PRODUCT = 2;





