USE [SaleManagementSystem]
GO

/****** Object:  View [dbo].[VW_CUSTOMERS_WITH_NO_PURCHASES]    Script Date: 15/01/2026 18:12:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_CUSTOMERS_WITH_NO_PURCHASES] AS
SELECT C.ID_CLIENT, C.NAME_CLIENT FROM CLIENT C
LEFT JOIN SALE S ON S.ID_CLIENT = C.ID_CLIENT
WHERE S.ID_CLIENT IS NULL;
GO


USE [SaleManagementSystem]
GO

/****** Object:  View [dbo].[VW_LOW_STOCK]    Script Date: 15/01/2026 18:13:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE   VIEW [dbo].[VW_LOW_STOCK] AS
SELECT P.NAME_PRODUCT, P.STOCK FROM PRODUCT P
WHERE P.STOCK < 5;
GO


USE [SaleManagementSystem]
GO

/****** Object:  View [dbo].[VW_SALES_DETAIL]    Script Date: 15/01/2026 18:15:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE   VIEW [dbo].[VW_SALES_DETAIL] AS
SELECT
    S.ID_SALE,
    C.NAME_CLIENT,
    C.CPF,
    P.NAME_PRODUCT,
    P.PRICE,
    SI.QUANTITY,
    SI.TOTAL,
    S.SALE_DATE
FROM CLIENT C
INNER JOIN SALE S ON S.ID_CLIENT = C.ID_CLIENT
INNER JOIN SALE_ITEM SI ON SI.ID_SALE = S.ID_SALE
INNER JOIN PRODUCT P ON P.ID_PRODUCT = SI.ID_PRODUCT
WHERE C.STATUS = 1;
GO


